# Generated by Django 2.2.24 on 2022-04-30 17:15

from django.apps.registry import Apps
from django.db import migrations
from django.db.models import Q


def new_building(apps: Apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    new_building_year = 2014
    Flat.objects.update(is_building_new=Q(construction_year__gte=new_building_year))


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(new_building)
    ]
