# Generated by Django 2.2.24 on 2022-04-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20220430_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(db_index=True, verbose_name='Новостройка'),
        ),
    ]
