# Generated by Django 2.2.24 on 2022-04-30 18:40
import phonenumbers
from django.db import migrations

def resolve_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        phonenumber = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(phonenumber):
            flat.owner_pure_phone = phonenumber
            flat.save()
        flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20220430_2324'),
    ]

    operations = [
        migrations.RunPython(resolve_phone_numbers)
    ]
