# Generated by Django 2.2.24 on 2022-04-30 19:01
import phonenumbers
from django.db import migrations

def resolve_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        phonenumber = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number_for_region(phonenumber, 'RU'):
            flat.owners_pure_phone = phonenumber
        else:
            flat.owners_pure_phone = None
        flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20220430_2347'),
    ]

    operations = [
        migrations.RunPython(resolve_phone_numbers)
    ]
