# Generated by Django 2.2.24 on 2022-05-01 05:25

from django.db import migrations

def remove_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner, _ = Owner.objects.get_or_create(
            fullname=flat.owner,
            phone=flat.owners_phonenumber,
            pure_phone=flat.owner_pure_phone
        )
        owner.flats.add(flat)
        owner.save()



class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_owner'),
    ]

    operations = [
        migrations.RunPython(remove_owners),
    ]
